version: '3.5'
services:

  jupyterhub:
    build: ./jupyterhub/
    ports:
      - 127.0.0.1:8000:8000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./jupyterhub/jupyterhub_config.py:/srv/jupyterhub/jupyterhub_config.py:ro
      - /jupyterhub_users:/jupyterhub_users:rw
    networks:
      - viscode
    environment:
      JUPYTERHUB_AUTH_METHOD: Default
      # LTI_CLIENT_KEY: 5282f7bfd4d5845684e6775a715b1aebe3d3001afc05a9bb0114f4cd71ac9a0a
      # LTI_CLIENT_SECRET: 1747cfa7de220ef5dcc7b2d2a5ad32e83665fedb87c1623d639dc015ffe8f547
      # LTI_USER_ID_FIELD: ext_user_username
      # JUPYTERHUB_CRYPT_KEY: 94d02234afb5ce12bf8c045ec3d8cc4c1166f196f76d6ac4e2ca6f8eb5b2bf66
    env_file:
      - 'database.env'
    depends_on:
      - postgres

  postgres:
    build: ./postgres/
    restart: always
    environment:
      POSTGRES_USER: kslab
      POSTGRES_PASSWORD: Kslab35356
    volumes:
      - "./postgres/data:/var/lib/postgresql/data"
    ports:
      - 127.0.0.1:5432:5432
    networks:
      - viscode

  adminer:
    image: adminer
    restart: always
    ports:
      - 127.0.0.1:8080:8080
    networks:
      - viscode

  viscode-api:
    build: ./viscode-api-server/
    ports:
      - 127.0.0.1:5000:80
    networks:
      - viscode
    environment:
      ELASTICSEARCH_HOSTS: es01,es02
      USE_MONGODB: 1
      MONGODB_HOST: 140.115.53.147
      MONGODB_USER: readWrite_user
      MONGODB_PASSWORD: kslab_readwrite
    env_file:
      - 'database.env'
    depends_on:
      - es01
      - es02
      - postgres
      
  es01:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.3.1
    restart: always
    volumes:
      - ./elasticsearch/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml:ro
      - ./elasticsearch/esdata01:/usr/share/elasticsearch/data
    ports:
      - 127.0.0.1:9200:9200
      - 127.0.0.1:9300:9300
    networks:
      - viscode
    environment:
      - node.name=es01
      - discovery.seed_hosts=es02
      - cluster.initial_master_nodes=es01,es02

      # discovery.type: single-node
      # ELASTIC_PASSWORD: ncukslksl
      # network.host: "_non_loopback_"
      - cluster.name=viscode-cluster
      - bootstrap.memory_lock=true
      # discovery.type: zen
      # discovery.zen.ping.unicast.hosts: es01
    ulimits:
      memlock:
        soft: -1
        hard: -1

  es02:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.3.1
    restart: always
    volumes:
      - ./elasticsearch/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml:ro
      - ./elasticsearch/esdata02:/usr/share/elasticsearch/data
    ports:
      - 127.0.0.1:9201:9200
      - 127.0.0.1:9301:9300
    networks:
      - viscode
    environment:
      - node.name=es02
      - discovery.seed_hosts=es01
      - cluster.initial_master_nodes=es01,es02
      # discovery.type: single-node
      # ELASTIC_PASSWORD: ncukslksl
      # network.host: "_non_loopback_"
      - cluster.name=viscode-cluster
      - bootstrap.memory_lock=true
      # discovery.type: zen
      # discovery.zen.ping.unicast.hosts: es01
    ulimits:
      memlock:
        soft: -1
        hard: -1

  kibana:
    image: docker.elastic.co/kibana/kibana:7.3.1
    volumes:
      - ./kibana/config/kibana.yml:/usr/share/kibana/config/kibana.yml:ro
    restart: always
    ports:
      - 127.0.0.1:5601:5601
    networks:
      - viscode
    # environment:
      # ELASTICSEARCH_URL: http://127.0.0.1:9200
      # ELASTICSEARCH_USERNAME: elastic
      # ELASTICSEARCH_PASSWORD: ncukslksl
    depends_on:
      - es01

networks:
  viscode:
    name: viscode_viscode
    driver: bridge
    
